networks:
  transaction_processing_service-net:
    driver: bridge

services:
  transaction_processing_service:
    container_name: 'transaction_processing_service'
    image: transaction-processing-service:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      cassandra:
        condition: service_healthy
    networks:
      - transaction_processing_service-net

  postgres:
    container_name: 'postgres_container'
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'postgres_db'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      PGDATA: "/var/lib/postgres"
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      LC_MESSAGES: en_US.UTF-8
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgres
    networks:
      - transaction_processing_service-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres_db" ]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3
    restart: on-failure
    tty: true
    stdin_open: true

  cassandra:
    container_name: 'cassandra-1'
    image: 'cassandra:latest'
    stop_signal: SIGTERM
    stop_grace_period: 60s
    networks:
      - transaction_processing_service-net
    environment:
      CASSANDRA_DC: 'exchange_rate_datacenter_1'
      CASSANDRA_ENDPOINT_SNITCH: 'SimpleSnitch'
      CASSANDRA_NUM_TOKENS: '1'
      JVM_OPTS: >
        -Xms512M
        -Xmx1G
        -Dcassandra.skip_wait_for_gossip_to_settle=0
        -Dcassandra.initial_token=1
        -Dcassandra.allocate_tokens_for_local_replication_factor=1
    ports:
      - '9042:9042'
    volumes:
      - cassandra-node:/var/lib/cassandra
    restart:
      unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1.5G
        reservations:
          memory: 512M
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' || exit 1" ]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3
    command: >
      bash -c '
      echo "JVM_OPTS=\"$$JVM_OPTS -Dcassandra.superuser_setup_delay_ms=0\"" >> /etc/cassandra/jvm-server.options;
      trap "echo \"Stopping Cassandra\"; nodetool stopdaemon" SIGTERM;
      exec /usr/local/bin/docker-entrypoint.sh
      '

volumes:
  postgres-data:
  pgadmin-data:
  cassandra-node: